config/routes.rb
Rails.application.routes.draw do
  resources :weatherrs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'weatherrs#index'
  get '/find',to: 'weatherrs#find', as: 'find'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/weatherr.rb
class Weatherr < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/weatherrs_controller.rb
class WeatherrsController < ApplicationController
  before_action :set_weatherr, only: [:show, :edit, :update, :destroy]

  # GET /weatherrs
  # GET /weatherrs.json
  def index
    @weatherrs = Weatherr.last(30).reverse
  end
  def update
  end
  def find
    @yy = params[:year]
    @mm = params[:month]
    @dd = params[:day]
    system "bin/rake update[#{@yy},#{@mm},#{@dd}]"
    redirect_to weatherrs_path
  end
  def show
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_weatherr
    @weatherr = Weatherr.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weatherrs_helper.rb
module WeatherrsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-TW">
  <head>
    <title>東吉管理站-自動化業務 Version 2.2.0</title>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- navbar -->
    <header class="navbar navbar-dark navbar-full navbar-fixed-top bg-primary">
      <div class="container-fluid">
        <nav>
          <div class="clearfix">
            <button class="navbar-toggler hidden-sm-up btn-primary btn-lg pull-xs-right" type="button" data-toggle="collapse" data-target="#nav_menu" aria-controls="nav_menu" aria-expanded="false" aria-label="Toggle navigation">
            &#9776;
            </button>
            <div><%= link_to "東吉管理站" , root_path , class: "navbar-brand h1 hidden-sm-up" %></div>

          </div>
          <div id="nav_menu" class="collapse navbar-toggleable-xs" >
            <div class="nav navbar-nav" >
              <div><%= link_to "東吉管理站" , root_path , class: "navbar-brand h1 hidden-xs-down" %></div>
              <a class="nav-item nav-link active" href="#">氣象資料 <span class="sr-only">(current)</span></a>
              <a class="nav-item nav-link " href="#">其他</a>
              <a class="nav-item nav-link pull-sm-right" href="#">登入</a>
              <a class="nav-item nav-link pull-sm-right" href="#">註冊</a>
            </div>
          </div>
        </nav>
      </div>
    </header>





    <!-- content area -->


    <%= yield %>

  </body>
</html>

app/views/weatherrs/index.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">更新氣象資料</h4>
      </div>
      <div class="modal-body">
        <!-- content here -->
        <%= form_tag find_path, method: "get" do %>
          <%= label_tag(:year, "年（民國）yyy:") %>
          <%= text_field_tag :year, params[:year] %>
          <br>
          <%= label_tag(:month, "月(雙位數)mm:") %>
          <%= text_field_tag :month, params[:month] %>
          <br>
          <%= label_tag(:day, "日（雙位數）dd:") %>
          <%= text_field_tag :day, params[:day] %>
          <hr>
          <%= submit_tag("更新") %>
        <% end %>
      </div>
    </div>
  </div>
</div>




<!--一般內容 -->
<div class="container-fluid">
  <div class="row">
    <div class="page-header">
      <div class="col-xs-8">
        <h2 class="h3">近30日氣象資料<span class="h6">--氣象局資料--</span></h2>
      </div>
      <div class="col-xs-4">
        <button type="button" class="btn btn-primary pull-xs-right btn-sm" data-toggle="modal" data-target="#myModal">
          更新天氣
        </button>
      </div>
    </div>
    <table class="table table-hover table-sm">
      <thead class="bg-primary">
        <tr>
          <th>日期</th>
          <th class="hidden-xs-down" data-toggle="tooltip" data-placement="top" data-original-title="單位：°C">氣溫</th>
          <th>最低溫</th>
          <th>最高溫</th>
          <th class="hidden-sm-down" data-toggle="tooltip" data-placement="top" data-original-title="單位：mm">累積雨量</th>
          <th class="hidden-lg-down" data-toggle="tooltip" data-placement="top" data-original-title="單位：hr">降雨時數</th>
          <th>日照率</th>
          <th>日照時數</th>
          <th data-toggle="tooltip" data-placement="top" data-original-title="單位：m/s">風速</th>
          <th data-toggle="tooltip" data-placement="top" data-original-title="單位：m/s">最大陣風</th>
          <th>相對濕度</th>
          <th class="hidden-lg-down" data-toggle="tooltip" data-placement="top" data-original-title="單位：hPa">海面氣壓</th>
          <th class="hidden-md-down" data-toggle="tooltip" data-placement="top" data-original-title="單位：km">能見度</th>
          <th class="hidden-xs-down">數據狀態</th>
        </tr>
      </thead>
      <tbody>
        <% @weatherrs.each do |report| %>
          <tr>
            <td><%= report.id %></td>
            <td class="hidden-xs-down"><%= report.temp %></td>
            <td><%= report.t_min %></td>
            <td><%= report.t_max %></td>
            <td class="hidden-sm-down" ><%= report.rain %></td>
            <td class="hidden-lg-down"><%= report.rain_hour %></td>
            <td><%= report.sun_rate %></td>
            <td><%= report.sun_hour %></td>
            <td><%= report.wdsd %></td>
            <td><%= report.wd_max %></td>
            <td><%= report.humd %></td>
            <td class="hidden-lg-down"><%= report.pres %></td>
            <td class="hidden-md-down"><%= report.visb %></td>
            <td class="hidden-xs-down"><%= report.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>